//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK_TABLE()
        {
            this.STATUS = true;
            this.ACTION_TABLE = new HashSet<ACTION_TABLE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<int> AUTHOR { get; set; }
        public string PRINTDATE { get; set; }
        public string PUBLISHER { get; set; }
        public string PAGE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTION_TABLE> ACTION_TABLE { get; set; }
        public virtual AUTHOR_TABLE AUTHOR_TABLE { get; set; }
        public virtual CATEGORY_TABLE CATEGORY_TABLE { get; set; }
    }
}
